name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.5', '2.6', '2.7']
    env:
      RAILS_VERSION: 6.0.0
      SQLITE3_VERSION: 1.4.1
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install libpq-dev
      run: sudo apt-get -yqq install libpq-dev
    - name: Install bundler
      run: gem install bundler
    - name: Run bundler
      run: bundle install --jobs 4 --retry 3
    - name: Run Rake
      run: bundle exec rake
